version: '3.8'
services:
    frontend:
        image: todo-frontend
        build: ./todo-frontend
        restart: always
        expose:
            - 3000
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - app-network     
    mongo:
        image: mongo
        ports:
        - 3456:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: todo-database     
    backend:
        image: todo-backend
        build: ./todo-backend
        env_file:
            - ./todo-backend/.env
        expose:
            - 3000
        ports:
            - 8000:3000
        environment:
            MONGO_URL: mongodb+srv://fullstack:12345@fullstack.bu2xfaj.mongodb.net/todos
        depends_on:
            - mongo
        networks:
            - app-network
    # nginx:
    #     image: nginx:1.13 # this will use the latest version of 1.13.x
    #     ports:
    #     - '80:80' # expose 80 on host and sent to 80 in container
    #     depends_on: 
    #     - frontend
    #     - backend
    #     - mongo
    #     volumes:
    #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
    app-network:
        driver: bridge

volumes:
    database
