version: '3.8'
services:

    frontend:
        image: todo-frontend
        build: ./todo-frontend
        expose:
            - 3000
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - app-network
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - 3456:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: the_database
        volumes: 
            - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
            - todoapp:/data/db
        networks:
            - app-network
    backend:
        image: todo-backend
        build: ./todo-backend
        env_file: ./todo-backend/.env
        restart: always
        expose:
            - 3000
        ports:
            - 8000:3000
        volumes:
            - /Users/nhattuandao/bclearn/part12-containers-applications/todo-app/todo-backend:/usr/src/app
        links: 
            - mongo
        depends_on: 
            - mongo
        networks:
            - app-network

volumes:
    todoapp:

networks:
    app-network:
        driver: bridge
